print("Введите 5 чисел:")
num1 = float(input("Первое число: "))
num2 = float(input("Второе число: "))
num3 = float(input("Третье число: "))
num4 = float(input("Четвертое число: "))
num5 = float(input("Пятое число: "))
min_value = min(num1, num2, num3, num4, num5)
max_value = max(num1, num2, num3, num4, num5)
print("\nРезультаты:")
print(f"Минимальное значение: {min_value}")
print(f"Максимальное значение: {max_value}")
