text = input("Введите текст")
word = input("Введите слово для поиска")
count = text.count(word)
index = text.find(word)
Rtext = text.replace(word, "")
print(f"Количество встреченных слов: {count}")
print(f"Индекс первого встреченного слова: {index}")
print("Текст без указанного слова:")
print(Rtext)
